/**
 * 共享启发式分析器
 * @author Cursor
 * @date 2026-06-28
 */
import { GENERIC_NAMES, IDENTIFIER_STOP_WORDS } from '../constants';
import { FeatureContribution, FileAnalysis, FileSignals } from '../types';

export function clampScore(value: number): number {
  return Math.max(0, Math.min(100, Math.round(value)));
}

export function computeCommentDensity(source: string): number {
  const lines = source.split('\n');
  if (lines.length === 0) return 0;
  const commentLines = lines.filter((l) => /^\s*(#|\/\/|\/\*|\*|"""|''')/.test(l)).length;
  const ratio = commentLines / lines.length;
  return clampScore(ratio * 280);
}

export function computeGenericNameRatio(source: string): number {
  const identifiers = (source.match(/\b[a-zA-Z_][a-zA-Z0-9_]*\b/g) ?? []).filter(
    (id) => !IDENTIFIER_STOP_WORDS.has(id.toLowerCase()),
  );
  if (identifiers.length === 0) return 0;
  const genericCount = identifiers.filter((id) => GENERIC_NAMES.includes(id.toLowerCase())).length;
  return clampScore((genericCount / identifiers.length) * 450);
}

export function computeUniformityScore(source: string): number {
  const lines = source.split('\n').filter((l) => l.trim().length > 0);
  if (lines.length < 2) return 0;
  const lengths = lines.map((l) => l.length);
  const avg = lengths.reduce((a, b) => a + b, 0) / lengths.length;
  const variance = lengths.reduce((sum, len) => sum + (len - avg) ** 2, 0) / lengths.length;
  const stdDev = Math.sqrt(variance);
  return clampScore(Math.max(0, 100 - stdDev * 2.5));
}

export function computeBoilerplateScore(source: string): number {
  const patterns = [
    /try\s*{[\s\S]*?}\s*catch/g,
    /^import .+ from .+;$/gm,
    /console\.(log|error|warn)/g,
    /throw new \w+Error/g,
  ];
  let hits = 0;
  for (const p of patterns) {
    hits += (source.match(p) ?? []).length;
  }
  return clampScore(hits * 18);
}

/** 文件头或注释中的 AI / 生成标记 */
export function computeAiAuthorshipMarkers(source: string): number {
  const patterns = [
    /@author\s+(AI|Cursor|Copilot|ChatGPT|Claude|Assistant|Auto|GPT|Gemini)/i,
    /generated by/i,
    /auto-?generated/i,
    /created with (AI|Copilot|Cursor|ChatGPT|Claude)/i,
    /this (file|code) was (generated|created)/i,
  ];
  if (patterns.some((p) => p.test(source))) {
    return 95;
  }
  return 0;
}

/** 分节注释（# --- / // === 等，AI 生成代码常见） */
export function computeSectionDividerScore(source: string): number {
  const hits =
    source.match(/^[\t ]*(?:\/\/|#)\s*[-=*#]{3,}|^[\t ]*\/\/\s*(?:Section|Step|Part)\s+\d+/gim) ?? [];
  return clampScore(hits.length * 32);
}

/** 注释紧邻代码行（逐步讲解式注释） */
export function computeLineExplainCommentScore(source: string): number {
  const lines = source.split('\n');
  let pairs = 0;
  for (let i = 0; i < lines.length - 1; i++) {
    const comment = lines[i].trim();
    const next = lines[i + 1].trim();
    if (/^(\/\/|#|\*)\s+\S/.test(comment) && next.length > 0 && !/^(\/\/|#|\/\*|\*)/.test(next)) {
      pairs++;
    }
  }
  const codeLines = countCodeLines(source) || 1;
  return clampScore((pairs / codeLines) * 220);
}

/** 函数/方法结构高度相似（AI 批量生成常见） */
export function computeStructuralRegularity(source: string): number {
  const codeLines = countCodeLines(source);
  if (codeLines < 12) return 0;

  const blocks =
    source.match(
      /(?:function\s+\w+|async\s+function\s+\w+|(?:public|private|protected)\s+\w+\s+\w+\s*\([^)]*\)\s*\{)/g,
    ) ?? [];
  if (blocks.length < 3) return clampScore(blocks.length * 6);

  const bodies = source.split(/\{/).slice(1, 8);
  if (bodies.length < 3) return clampScore(blocks.length * 10);
  const lineCounts = bodies.map((b) => b.split('\n').length);
  const avg = lineCounts.reduce((a, b) => a + b, 0) / lineCounts.length;
  const variance =
    lineCounts.reduce((s, n) => s + (n - avg) ** 2, 0) / lineCounts.length;
  const regular = variance < 8 ? 85 : variance < 20 ? 55 : 20;
  let result = clampScore(regular + Math.min(blocks.length, 6) * 3);
  if (codeLines < 30) result = Math.min(result, 42);
  return result;
}

/** 命名偏长、偏描述性 */
export function computeVerboseNamingScore(source: string): number {
  const identifiers = source.match(/\b[a-z][a-zA-Z0-9]{11,}\b/g) ?? [];
  const total = source.match(/\b[a-zA-Z_][a-zA-Z0-9_]*\b/g)?.length ?? 0;
  if (total === 0) return 0;
  return clampScore((identifiers.length / total) * 350);
}

/** 防御性编程密度 */
export function computeDefensivePatternScore(source: string): number {
  let hits = 0;
  hits += (source.match(/\?\./g) ?? []).length;
  hits += (source.match(/\?\?/g) ?? []).length;
  hits += (source.match(/if\s*\([^)]*(?:null|undefined|!==|===)[^)]*\)/g) ?? []).length;
  hits += (source.match(/\.(?:trim|parseInt|parseFloat|String)\(/g) ?? []).length;
  return clampScore(hits * 12);
}

/** 平均标识符长度（排除关键字） */
export function computeAvgIdentifierLength(source: string): number {
  const identifiers = (source.match(/\b[a-zA-Z_][a-zA-Z0-9_]*\b/g) ?? []).filter(
    (id) => !IDENTIFIER_STOP_WORDS.has(id.toLowerCase()),
  );
  if (identifiers.length === 0) return 0;
  return identifiers.reduce((sum, id) => sum + id.length, 0) / identifiers.length;
}

/** 复述型注释（解释 obvious 逻辑，AI 常见） */
export function computeRestatingCommentScore(source: string): number {
  const lines = source.split('\n');
  let restating = 0;
  let totalComments = 0;
  const restatingPatterns = [
    /^\s*(\/\/|#|\*)\s*(increment|decrement|initialize|create|return|get|set|define|declare|import|export|call|invoke|loop|iterate|check|validate|handle)/i,
    /^\s*(\/\/|#|\*)\s*(the|a|an)\s+\w+/i,
    /^\s*(\/\/|#|\*)\s*(检查|获取|设置|返回|定义|导入|导出|循环|调用|验证|处理)/,
  ];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!/^\s*(#|\/\/|\/\*|\*)/.test(line)) continue;
    totalComments++;
    if (restatingPatterns.some((p) => p.test(line))) restating++;
    const next = lines[i + 1]?.trim() ?? '';
    if (/^\s*(\/\/|#)/.test(line) && /^(return|break|continue|\+\+|--|\w+\s*[+=])/.test(next)) {
      restating++;
    }
  }
  if (totalComments === 0) return 0;
  return clampScore((restating / totalComments) * 130);
}

/** 空行分布规律性（AI 排版更均匀） */
export function computeBlankLineRegularityScore(source: string): number {
  const lines = source.split('\n');
  const total = lines.length;
  if (total < 12) return 0;
  const blankCount = lines.filter((l) => l.trim() === '').length;
  const blankRatio = blankCount / total;
  if (blankRatio < 0.04) return 0;

  const blankRuns: number[] = [];
  let run = 0;
  for (const line of lines) {
    if (line.trim() === '') {
      run++;
    } else if (run > 0) {
      blankRuns.push(run);
      run = 0;
    }
  }
  if (run > 0) blankRuns.push(run);
  if (blankRuns.length < 2) return clampScore(blankRatio * 90);

  const avg = blankRuns.reduce((a, b) => a + b, 0) / blankRuns.length;
  const variance = blankRuns.reduce((s, n) => s + (n - avg) ** 2, 0) / blankRuns.length;
  const regularity = variance < 0.5 ? 88 : variance < 1.5 ? 58 : 28;
  return clampScore(regularity * Math.min(blankRatio * 4, 1));
}

/** catch 块只 log 不 rethrow（AI 常见防御性写法） */
export function computeCatchSwallowScore(source: string): number {
  const catches = source.match(/catch\s*\([^)]*\)\s*\{[^}]*\}/g) ?? [];
  if (catches.length === 0) return 0;
  const swallow = catches.filter(
    (block) =>
      /(console\.(log|error|warn|debug)|logger\.|print\(|System\.out)/i.test(block) && !/throw/.test(block),
  ).length;
  return clampScore((swallow / catches.length) * 100);
}

/** 人类代码痕迹（FIXME/debug 等，越高越像人类手写） */
export function computeHumanTraceScore(source: string): number {
  let hits = 0;
  hits += (source.match(/\b(FIXME|HACK|XXX|WORKAROUND|HOTFIX)\b/gi) ?? []).length * 28;
  hits += (source.match(/\bdebugger\b/g) ?? []).length * 35;
  hits += (source.match(/console\.(log|debug)\(/g) ?? []).length * 10;
  hits += (source.match(/\/\/.*(messy|fix later|don'?t touch|wtf|ugly|deprecated|tmp|temp)/gi) ?? []).length * 22;
  hits += (source.match(/^\s*#.*(legacy|workaround|fixme)/gim) ?? []).length * 18;
  return clampScore(hits);
}

/** 提取单文件风格指标 */
export function extractFileSignals(source: string): FileSignals {
  const lines = source.split('\n');
  const total = lines.length || 1;
  const commentLines = lines.filter((l) => /^\s*(#|\/\/|\/\*|\*|"""|''')/.test(l)).length;
  const blankLines = lines.filter((l) => l.trim() === '').length;
  return {
    commentRatio: commentLines / total,
    avgNameLength: computeAvgIdentifierLength(source),
    blankLineRatio: blankLines / total,
    restatingComment: computeRestatingCommentScore(source),
    blankLineRegularity: computeBlankLineRegularityScore(source),
    catchSwallow: computeCatchSwallowScore(source),
    humanTrace: computeHumanTraceScore(source),
  };
}

const P0_FEATURE_WEIGHTS = {
  restatingComments: 0.09,
  blankLineRegularity: 0.07,
  catchSwallow: 0.08,
} as const;

/** 合并特征、P0 信号并应用人类痕迹降权 */
export function finalizeFileAnalysis(
  relativePath: string,
  source: string,
  language: FileAnalysis['language'],
  features: FeatureContribution[],
): FileAnalysis {
  const signals = extractFileSignals(source);
  const allFeatures: FeatureContribution[] = [
    ...features,
    { name: 'restatingComments', score: signals.restatingComment, weight: P0_FEATURE_WEIGHTS.restatingComments },
    { name: 'blankLineRegularity', score: signals.blankLineRegularity, weight: P0_FEATURE_WEIGHTS.blankLineRegularity },
    { name: 'catchSwallow', score: signals.catchSwallow, weight: P0_FEATURE_WEIGHTS.catchSwallow },
  ];
  const { score, topFeatures } = combineFeatures(allFeatures);
  const humanPenalty = Math.min(30, Math.round(signals.humanTrace * 0.38));
  return {
    relativePath,
    language,
    codeLines: countCodeLines(source),
    fileScore: clampScore(score - humanPenalty),
    topFeatures,
    signals,
  };
}

export function combineFeatures(features: FeatureContribution[]): { score: number; topFeatures: FeatureContribution[] } {
  const totalWeight = features.reduce((s, f) => s + f.weight, 0) || 1;
  const weightedAvg = features.reduce((s, f) => s + f.score * f.weight, 0) / totalWeight;
  const sorted = [...features].sort((a, b) => b.score - a.score);
  const top3Avg =
    sorted.slice(0, 3).reduce((s, f) => s + f.score, 0) / Math.min(3, sorted.length || 1);

  const highSignals = features.filter((f) => f.score >= 50).length;
  const moderateSignals = features.filter((f) => f.score >= 35).length;
  let boost = 0;
  if (highSignals >= 4) boost = 24;
  else if (highSignals >= 3) boost = 16;
  else if (highSignals >= 2) boost = 9;
  else if (moderateSignals >= 6) boost = 14;
  else if (moderateSignals >= 4) boost = 7;

  const marker = features.find((f) => f.name === 'aiMarkers' && f.score >= 90);
  let score = marker ? Math.max(weightedAvg, 90) : weightedAvg * 0.32 + top3Avg * 0.68 + boost;

  if (highSignals >= 4 && score < 70) score = 70;
  if (highSignals >= 5 && score < 78) score = 78;

  score = clampScore(score);

  const topFeatures = [...features].sort((a, b) => b.score * b.weight - a.score * a.weight).slice(0, 3);
  return { score, topFeatures };
}

export function countCodeLines(source: string): number {
  return source.split('\n').filter((l) => l.trim().length > 0 && !/^\s*(#|\/\/|\/\*|\*)/.test(l)).length;
}

/** 共享特征分析（Vue 等扩展名） */
export function analyzeWithSharedFeatures(
  relativePath: string,
  source: string,
  language: FileAnalysis['language'],
): FileAnalysis {
  const features = [
    { name: 'commentDensity', score: computeCommentDensity(source), weight: 0.1 },
    { name: 'genericNames', score: computeGenericNameRatio(source), weight: 0.1 },
    { name: 'uniformity', score: computeUniformityScore(source), weight: 0.09 },
    { name: 'boilerplate', score: computeBoilerplateScore(source), weight: 0.09 },
    { name: 'aiMarkers', score: computeAiAuthorshipMarkers(source), weight: 0.14 },
    { name: 'regularity', score: computeStructuralRegularity(source), weight: 0.12 },
    { name: 'verboseNaming', score: computeVerboseNamingScore(source), weight: 0.09 },
    { name: 'defensive', score: computeDefensivePatternScore(source), weight: 0.09 },
    { name: 'sectionDivider', score: computeSectionDividerScore(source), weight: 0.09 },
    { name: 'lineExplain', score: computeLineExplainCommentScore(source), weight: 0.09 },
  ];
  return finalizeFileAnalysis(relativePath, source, language, features);
}
