/**
 * 共享启发式分析器
 * @author Cursor
 * @date 2026-06-28
 */
import { GENERIC_NAMES } from '../constants';
import { FeatureContribution, FileAnalysis } from '../types';

export function clampScore(value: number): number {
  return Math.max(0, Math.min(100, Math.round(value)));
}

export function computeCommentDensity(source: string): number {
  const lines = source.split('\n');
  if (lines.length === 0) return 0;
  const commentLines = lines.filter((l) => /^\s*(#|\/\/|\/\*|\*|"""|''')/.test(l)).length;
  const ratio = commentLines / lines.length;
  return clampScore(ratio * 280);
}

export function computeGenericNameRatio(source: string): number {
  const identifiers = source.match(/\b[a-zA-Z_][a-zA-Z0-9_]*\b/g) ?? [];
  if (identifiers.length === 0) return 0;
  const genericCount = identifiers.filter((id) => GENERIC_NAMES.includes(id.toLowerCase())).length;
  return clampScore((genericCount / identifiers.length) * 400);
}

export function computeUniformityScore(source: string): number {
  const lines = source.split('\n').filter((l) => l.trim().length > 0);
  if (lines.length < 2) return 0;
  const lengths = lines.map((l) => l.length);
  const avg = lengths.reduce((a, b) => a + b, 0) / lengths.length;
  const variance = lengths.reduce((sum, len) => sum + (len - avg) ** 2, 0) / lengths.length;
  const stdDev = Math.sqrt(variance);
  return clampScore(Math.max(0, 100 - stdDev * 2.5));
}

export function computeBoilerplateScore(source: string): number {
  const patterns = [
    /try\s*{[\s\S]*?}\s*catch/g,
    /^import .+ from .+;$/gm,
    /console\.(log|error|warn)/g,
    /throw new \w+Error/g,
  ];
  let hits = 0;
  for (const p of patterns) {
    hits += (source.match(p) ?? []).length;
  }
  return clampScore(hits * 18);
}

/** 文件头或注释中的 AI / 生成标记 */
export function computeAiAuthorshipMarkers(source: string): number {
  const patterns = [
    /@author\s+(AI|Cursor|Copilot|ChatGPT|Claude|Assistant|Auto)/i,
    /generated by/i,
    /auto-?generated/i,
    /created with (AI|Copilot|Cursor)/i,
  ];
  if (patterns.some((p) => p.test(source))) {
    return 95;
  }
  return 0;
}

/** 函数/方法结构高度相似（AI 批量生成常见） */
export function computeStructuralRegularity(source: string): number {
  const codeLines = countCodeLines(source);
  if (codeLines < 20) return 0;

  const blocks =
    source.match(
      /(?:function\s+\w+|async\s+function\s+\w+|(?:public|private|protected)\s+\w+\s+\w+\s*\([^)]*\)\s*\{)/g,
    ) ?? [];
  if (blocks.length < 3) return clampScore(blocks.length * 6);

  const bodies = source.split(/\{/).slice(1, 8);
  if (bodies.length < 3) return clampScore(blocks.length * 10);
  const lineCounts = bodies.map((b) => b.split('\n').length);
  const avg = lineCounts.reduce((a, b) => a + b, 0) / lineCounts.length;
  const variance =
    lineCounts.reduce((s, n) => s + (n - avg) ** 2, 0) / lineCounts.length;
  const regular = variance < 8 ? 85 : variance < 20 ? 55 : 20;
  return clampScore(regular + Math.min(blocks.length, 6) * 3);
}

/** 命名偏长、偏描述性 */
export function computeVerboseNamingScore(source: string): number {
  const identifiers = source.match(/\b[a-z][a-zA-Z0-9]{11,}\b/g) ?? [];
  const total = source.match(/\b[a-zA-Z_][a-zA-Z0-9_]*\b/g)?.length ?? 0;
  if (total === 0) return 0;
  return clampScore((identifiers.length / total) * 350);
}

/** 防御性编程密度 */
export function computeDefensivePatternScore(source: string): number {
  let hits = 0;
  hits += (source.match(/\?\./g) ?? []).length;
  hits += (source.match(/\?\?/g) ?? []).length;
  hits += (source.match(/if\s*\([^)]*(?:null|undefined|!==|===)[^)]*\)/g) ?? []).length;
  hits += (source.match(/\.(?:trim|parseInt|parseFloat|String)\(/g) ?? []).length;
  return clampScore(hits * 12);
}

export function combineFeatures(features: FeatureContribution[]): { score: number; topFeatures: FeatureContribution[] } {
  const totalWeight = features.reduce((s, f) => s + f.weight, 0) || 1;
  const weightedAvg = features.reduce((s, f) => s + f.score * f.weight, 0) / totalWeight;
  const sorted = [...features].sort((a, b) => b.score - a.score);
  const top3Avg =
    sorted.slice(0, 3).reduce((s, f) => s + f.score, 0) / Math.min(3, sorted.length || 1);

  const highSignals = features.filter((f) => f.score >= 55).length;
  let boost = 0;
  if (highSignals >= 4) boost = 18;
  else if (highSignals >= 3) boost = 12;
  else if (highSignals >= 2) boost = 6;

  const marker = features.find((f) => f.name === 'aiMarkers' && f.score >= 90);
  const score = clampScore(
    marker ? Math.max(weightedAvg, 88) : weightedAvg * 0.5 + top3Avg * 0.5 + boost,
  );

  const topFeatures = [...features].sort((a, b) => b.score * b.weight - a.score * a.weight).slice(0, 3);
  return { score, topFeatures };
}

export function countCodeLines(source: string): number {
  return source.split('\n').filter((l) => l.trim().length > 0 && !/^\s*(#|\/\/|\/\*|\*)/.test(l)).length;
}

/** 共享特征分析（Vue 等扩展名） */
export function analyzeWithSharedFeatures(
  relativePath: string,
  source: string,
  language: FileAnalysis['language'],
): FileAnalysis {
  const features = [
    { name: 'commentDensity', score: computeCommentDensity(source), weight: 0.12 },
    { name: 'genericNames', score: computeGenericNameRatio(source), weight: 0.12 },
    { name: 'uniformity', score: computeUniformityScore(source), weight: 0.12 },
    { name: 'boilerplate', score: computeBoilerplateScore(source), weight: 0.12 },
    { name: 'aiMarkers', score: computeAiAuthorshipMarkers(source), weight: 0.16 },
    { name: 'regularity', score: computeStructuralRegularity(source), weight: 0.14 },
    { name: 'verboseNaming', score: computeVerboseNamingScore(source), weight: 0.11 },
    { name: 'defensive', score: computeDefensivePatternScore(source), weight: 0.11 },
  ];
  const { score, topFeatures } = combineFeatures(features);
  return {
    relativePath,
    language,
    codeLines: countCodeLines(source),
    fileScore: score,
    topFeatures,
  };
}
